name: Phil B
favicon: null
layout_spectrum: 0.3659607502631843
typography_spectrum: 0.15722130984067917
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6204863821621984
  lightness: 0.358922413084656
  saturation: 0.44847653224132955
  rhythmicContrast: 0.03213074733503163
purpose: []
